In [1]:
import numpy as np
temperature_int=np.array([30,56,34,90,78])
print("Integer Temperature:",temperature_int)
print("Data Type:",temperature_int.dtype)
temperature_float = temperature_int.astype('f')
print("\nConverted to Float:", temperature_float)
print("Data Type:", temperature_float.dtype)
high_temp=temperature_float>30
print("\nHigh Temperature Flags:",high_temp)
print("Data Type:",high_temp.dtype)
print("\nMemory Used (int):", temperature_int.nbytes, "bytes")
print("Memory Used (float):", temperature_float.nbytes, "bytes")

Integer Temperature: [30 56 34 90 78]
Data Type: int32

Converted to Float: [30. 56. 34. 90. 78.]
Data Type: float32

High Temperature Flags: [False  True  True  True  True]
Data Type: bool

Memory Used (int): 20 bytes
Memory Used (float): 20 bytes


In [3]:
import numpy as np
book_ids=np.array([101,445,380,263,537,906])
print("Library Book IDs:",book_ids)
search_id=380
result=np.where(book_ids==search_id)
print(f"\nBook ID {search_id} found at position:",result[0])
high_id_books=np.where(book_ids>200)
print("\nBooks with ID>200 found at position:",high_id_books[0])

Library Book IDs: [101 445 380 263 537 906]

Book ID 380 found at position: [2]

Books with ID>200 found at position: [1 2 3 4 5]


In [5]:
import numpy as np
zero_matrix=np.zeros((5,5))
one_matrix=np.ones((6,6))
identity_matrix=np.eye(3)
random_matrix=np.random.randint(1,20,(5,5))
float_array=np.array([1,2,3,4,5],dtype='f')
print("Zero Matrix:\n",zero_matrix)
print("One Matrix:\n",one_matrix)
print("Identity Matrix:\n",identity_matrix)
print("Random Matrix:\n",identity_matrix)
print("Float Array:",float_array)

Zero Matrix:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
One Matrix:
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Float Array: [1. 2. 3. 4. 5.]
