In [2]:
import numpy as np
aqi=np.array([56,73,29,53,100,78,560,45,89,12])
print("AQI Values:",aqi)
polluted_days=aqi[aqi>50]
print("\nPolluted Days (AQI>50):",polluted_days)
safe_days=aqi[aqi<40]
print("Safe Days (AQI<40):",safe_days)

AQI Values: [ 56  73  29  53 100  78 560  45  89  12]

Polluted Days (AQI>50): [ 56  73  53 100  78 560  89]
Safe Days (AQI<40): [29 12]


In [1]:
import numpy as np
seats = np.zeros((7,6))
print("Seating Layout:\n", seats)
print("\nShape of seating arrangement:", seats.shape)
rows, columns = seats.shape
print("Number of rows:", rows)
print("Number of columns:", columns)
total_seats = rows * columns
print("Total Seats:", total_seats)
reshaped_seats = seats.reshape(2,21)
print("\nReshaped Seating Layout:\n", reshaped_seats)
print("New Shape:", reshaped_seats.shape)

Seating Layout:
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

Shape of seating arrangement: (7, 6)
Number of rows: 7
Number of columns: 6
Total Seats: 42

Reshaped Seating Layout:
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
New Shape: (2, 21)


In [3]:
import numpy as np
steps=np.array([1000,4000,3000,5000,2000])
heart_rate=np.array([80,85,78,90,98])
calories=np.array([400,245,346,683,386])
print("Steps:",steps)
print("Heart rate:",heart_rate)
print("Calories:",calories)
combined_h=np.hstack((steps,heart_rate,calories))
print("\nHorizontal Stack:\n",combined_h)
combined_v=np.vstack((steps,heart_rate,calories))
print("\nVertical Stack:\n",combined_v)
combined_stack=np.stack((steps,heart_rate,calories),axis=1)
print("\nStack with axis=1:\n",combined_stack)
combined_concat=np.concatenate((steps,heart_rate))
print("\nConcatenate Steps+Heart Rate:\n",combined_concat)


Steps: [1000 4000 3000 5000 2000]
Heart rate: [80 85 78 90 98]
Calories: [400 245 346 683 386]

Horizontal Stack:
 [1000 4000 3000 5000 2000   80   85   78   90   98  400  245  346  683
  386]

Vertical Stack:
 [[1000 4000 3000 5000 2000]
 [  80   85   78   90   98]
 [ 400  245  346  683  386]]

Stack with axis=1:
 [[1000   80  400]
 [4000   85  245]
 [3000   78  346]
 [5000   90  683]
 [2000   98  386]]

Concatenate Steps+Heart Rate:
 [1000 4000 3000 5000 2000   80   85   78   90   98]
