In [7]:
import numpy as np
marks=np.array([
    [75,75,90],
    [84,78,46],
    [67,90,76],
    [90,98,96]
])
print("All Marks:\n",marks)
print("First Rank:\n",marks[3])
print("Second Rank:\n",marks[2])
print("Third Rank:\n",marks[1])
print("Last Rank:\n",marks[0])

All Marks:
 [[75 75 90]
 [84 78 46]
 [67 90 76]
 [90 98 96]]
First Rank:
 [90 98 96]
Second Rank:
 [67 90 76]
Third Rank:
 [84 78 46]
Last Rank:
 [75 75 90]


In [9]:
import numpy as np
days=np.arange(1,51)
temperature=np.random.randint(24,40,size=50)
trend=np.linspace(34,65,90)
print("Days:\n",days)
print("Temperature:\n",temperature)
print("Trend:\n",trend)

Days:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
Temperature:
 [28 35 26 29 30 37 36 37 28 25 31 35 26 30 29 33 39 30 36 36 33 29 37 26
 24 31 35 39 27 35 39 37 36 31 33 34 35 32 26 27 29 30 34 37 24 26 36 32
 25 27]
Trend:
 [34.         34.34831461 34.69662921 35.04494382 35.39325843 35.74157303
 36.08988764 36.43820225 36.78651685 37.13483146 37.48314607 37.83146067
 38.17977528 38.52808989 38.87640449 39.2247191  39.57303371 39.92134831
 40.26966292 40.61797753 40.96629213 41.31460674 41.66292135 42.01123596
 42.35955056 42.70786517 43.05617978 43.40449438 43.75280899 44.1011236
 44.4494382  44.79775281 45.14606742 45.49438202 45.84269663 46.19101124
 46.53932584 46.88764045 47.23595506 47.58426966 47.93258427 48.28089888
 48.62921348 48.97752809 49.3258427  49.6741573  50.02247191 50.37078652
 50.71910112 51.06741573 51.41573034 51.76404494 52.11235955 52.46067416
 52.808

In [11]:
import numpy as np
weather=np.array([
    [35,78,23,56],
    [65,12,89,45],
    [67,90,36,87]
])
print("Weekly Weather Data:\n",weather)
print("\nCity-wise temperature:")
for city in weather:
    print(city)
print("\nAll temperature values:")
for temp in np.nditer(weather):
    print(temp,end=" ")
print("\n\nTemperature with position:")
for index, value in np.ndenumerate(weather):
    print("City", index[0],"Day",index[1],"=",value)
print("\nHigh Temperature Days(>20):")
for temp in np.nditer(weather):
    if(temp>20):
        print(temp)

Weekly Weather Data:
 [[35 78 23 56]
 [65 12 89 45]
 [67 90 36 87]]

City-wise temperature:
[35 78 23 56]
[65 12 89 45]
[67 90 36 87]

All temperature values:
35 78 23 56 65 12 89 45 67 90 36 87 

Temperature with position:
City 0 Day 0 = 35
City 0 Day 1 = 78
City 0 Day 2 = 23
City 0 Day 3 = 56
City 1 Day 0 = 65
City 1 Day 1 = 12
City 1 Day 2 = 89
City 1 Day 3 = 45
City 2 Day 0 = 67
City 2 Day 1 = 90
City 2 Day 2 = 36
City 2 Day 3 = 87

High Temperature Days(>20):
35
78
23
56
65
89
45
67
90
36
87
