In [1]:
import numpy as np
sales=np.array([
    [2000,4300,8900,1200],
    [4900,7689,2134,4300],
    [3000,5488,1990,5000],
    [6800,5433,7666,1999]
])
print("Full Sales Data:\n",sales)
q1=sales[0:2]
print("\nFirst 2 months:\n",q1)
q2=sales[-3:]
print("\nLast 3 months:\n",q2)
q3=sales[:,1]
print("\nProduct 2 Sales:\n",q3)
subset=sales[0:3,0:1]
print("\nSubset Data:\n",subset)

Full Sales Data:
 [[2000 4300 8900 1200]
 [4900 7689 2134 4300]
 [3000 5488 1990 5000]
 [6800 5433 7666 1999]]

First 2 months:
 [[2000 4300 8900 1200]
 [4900 7689 2134 4300]]

Last 3 months:
 [[4900 7689 2134 4300]
 [3000 5488 1990 5000]
 [6800 5433 7666 1999]]

Product 2 Sales:
 [4300 7689 5488 5433]

Subset Data:
 [[2000]
 [4900]
 [3000]]


In [3]:
import numpy as np
scores=np.array([540,745,230,600,894])
print("Original Scores:",scores)
sorted_scores=np.sort(scores)
print("Sorted Scores (Ascending):",sorted_scores)
level_scores=np.array([
    [540,745,230],
    [600,894,900]
])
print("\nOriginal Level Scores:\n",level_scores)
sorted_level_scores=np.sort(level_scores)
print("\nSorted Level Scores (Row-wise):\n",sorted_level_scores)

Original Scores: [540 745 230 600 894]
Sorted Scores (Ascending): [230 540 600 745 894]

Original Level Scores:
 [[540 745 230]
 [600 894 900]]

Sorted Level Scores (Row-wise):
 [[230 540 745]
 [600 894 900]]


In [5]:
import numpy as np
roll_num=np.arange(1,20)
salary_range=np.linspace(10000,500000,5)
attendance=np.zeros((5,3))
status=np.ones(5)
marks=np.random.randint(40,100,size=(5,3))
print("Roll Numbers:",roll_num)
print("Salary Range:",salary_range)
print("Attendance:\n",attendance)
print("Status:",status)
print("Marks:\n",marks)

Roll Numbers: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Salary Range: [ 10000. 132500. 255000. 377500. 500000.]
Attendance:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Status: [1. 1. 1. 1. 1.]
Marks:
 [[41 74 51]
 [96 78 46]
 [80 51 97]
 [74 41 57]
 [96 93 74]]
